package com.moneycontrol.mavenproject1.VIEW.ADMIN;

import com.moneycontrol.mavenproject1.DAO.ProcessDAO;
import com.moneycontrol.mavenproject1.DTO.ProcessDTO;
import javax.swing.JOptionPane;

public class AddDespesaADMINVIEW extends javax.swing.JFrame {

    /**
     * Creates new form addDespesaVIEW
     */
    public AddDespesaADMINVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agenciaTextfield = new javax.swing.JTextField();
        parcelasTextfield = new javax.swing.JTextField();
        parcelas_pagasTextfield = new javax.swing.JTextField();
        tipo_despesaTextfield = new javax.swing.JTextField();
        valor_despesaTextfield = new javax.swing.JTextField();
        despesaTextfield = new javax.swing.JTextField();
        backBTN_addDespesa = new javax.swing.JButton();
        contaTextfield = new javax.swing.JTextField();
        addDespesaBTN_addDespesa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        agenciaTextfield.setBackground(new java.awt.Color(51, 51, 51));
        agenciaTextfield.setForeground(new java.awt.Color(255, 255, 255));
        agenciaTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(agenciaTextfield);
        agenciaTextfield.setBounds(29, 462, 596, 60);

        parcelasTextfield.setBackground(new java.awt.Color(51, 51, 51));
        parcelasTextfield.setForeground(new java.awt.Color(255, 255, 255));
        parcelasTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(parcelasTextfield);
        parcelasTextfield.setBounds(29, 298, 596, 60);

        parcelas_pagasTextfield.setBackground(new java.awt.Color(51, 51, 51));
        parcelas_pagasTextfield.setForeground(new java.awt.Color(255, 255, 255));
        parcelas_pagasTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas Pagas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        parcelas_pagasTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelas_pagasTextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(parcelas_pagasTextfield);
        parcelas_pagasTextfield.setBounds(29, 384, 596, 60);

        tipo_despesaTextfield.setBackground(new java.awt.Color(51, 51, 51));
        tipo_despesaTextfield.setForeground(new java.awt.Color(255, 255, 255));
        tipo_despesaTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite o tipo de despesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(tipo_despesaTextfield);
        tipo_despesaTextfield.setBounds(29, 148, 596, 60);

        valor_despesaTextfield.setBackground(new java.awt.Color(51, 51, 51));
        valor_despesaTextfield.setForeground(new java.awt.Color(255, 255, 255));
        valor_despesaTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite o valor da despesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(valor_despesaTextfield);
        valor_despesaTextfield.setBounds(29, 226, 596, 60);

        despesaTextfield.setBackground(new java.awt.Color(51, 51, 51));
        despesaTextfield.setForeground(new java.awt.Color(255, 255, 255));
        despesaTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite sua despesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        despesaTextfield.setCaretColor(new java.awt.Color(255, 255, 255));
        despesaTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despesaTextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(despesaTextfield);
        despesaTextfield.setBounds(29, 70, 596, 60);

        backBTN_addDespesa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backBTN_addDespesa.setText("VOLTAR");
        backBTN_addDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN_addDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN_addDespesa);
        backBTN_addDespesa.setBounds(799, 25, 100, 28);

        contaTextfield.setBackground(new java.awt.Color(51, 51, 51));
        contaTextfield.setForeground(new java.awt.Color(255, 255, 255));
        contaTextfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        contaTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaTextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contaTextfield);
        contaTextfield.setBounds(29, 540, 596, 61);

        addDespesaBTN_addDespesa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addDespesaBTN_addDespesa.setText("ADICIONAR");
        addDespesaBTN_addDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDespesaBTN_addDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(addDespesaBTN_addDespesa);
        addDespesaBTN_addDespesa.setBounds(769, 562, 130, 28);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adicionar Despesas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(29, 6, 290, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\Tech Lines.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 410, 650);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\FundoPreto.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 910, 630);

        setSize(new java.awt.Dimension(919, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void parcelas_pagasTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelas_pagasTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parcelas_pagasTextfieldActionPerformed

    private void contaTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contaTextfieldActionPerformed

    //BOTAO ADICIONAR DESPESA
    private void addDespesaBTN_addDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDespesaBTN_addDespesaActionPerformed
        // TODO add your handling code here:

        String despesa;
        String tipo_despesa;
        String valor_despesa;
        String parcelas;
        String parcelas_pagas;
        String agencia;
        String conta;

        //pegando o texto dos imputs
        despesa = despesaTextfield.getText();
        tipo_despesa = tipo_despesaTextfield.getText();
        valor_despesa = valor_despesaTextfield.getText();
        parcelas = parcelasTextfield.getText();
        parcelas_pagas = parcelas_pagasTextfield.getText();
        agencia = agenciaTextfield.getText();
        conta = contaTextfield.getText();

        //instanciando novo DTO
        ProcessDTO processDTO = new ProcessDTO();
        processDTO.setDespesa(despesa);
        processDTO.setTipo_despesa(tipo_despesa);
        processDTO.setValor_despesa(valor_despesa);
        processDTO.setParcelas(parcelas);
        processDTO.setParcelas_pagas(parcelas_pagas);
        processDTO.setAgencia(agencia);
        processDTO.setConta(conta);

        //instanciando novo DAO que vai chamar a função
        ProcessDAO processDAO = new ProcessDAO();

        //chamando a função
        processDAO.cadastraDespesa(processDTO);

        //mensagem de sucesso
        JOptionPane.showMessageDialog(null, "despesa adicionada com sucesso");
        this.dispose();

        //redirecionando para a pagina principal
        MoneyControlADMINVIEW moneycontroladminVIEW = new MoneyControlADMINVIEW();
        moneycontroladminVIEW.setVisible(true);


    }//GEN-LAST:event_addDespesaBTN_addDespesaActionPerformed

    private void despesaTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despesaTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_despesaTextfieldActionPerformed

    //BOTÃO VOLTAR
    private void backBTN_addDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN_addDespesaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MoneyControlADMINVIEW moneycontroladminVIEW = new MoneyControlADMINVIEW();
        moneycontroladminVIEW.setVisible(true);
    }//GEN-LAST:event_backBTN_addDespesaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDespesaBTN_addDespesa;
    private javax.swing.JTextField agenciaTextfield;
    private javax.swing.JButton backBTN_addDespesa;
    private javax.swing.JTextField contaTextfield;
    private javax.swing.JTextField despesaTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField parcelasTextfield;
    private javax.swing.JTextField parcelas_pagasTextfield;
    private javax.swing.JTextField tipo_despesaTextfield;
    private javax.swing.JTextField valor_despesaTextfield;
    // End of variables declaration//GEN-END:variables
}
