package com.moneycontrol.mavenproject1.VIEW.ADMIN;

import com.moneycontrol.mavenproject1.DAO.AdminDAO;
import com.moneycontrol.mavenproject1.DTO.UsuarioDTO;
import javax.swing.JOptionPane;


public class AddUsuarioVIEW extends javax.swing.JFrame {

    /**
     * Creates new form AddUsuarioVIEW
     */
    public AddUsuarioVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        inputUsuarioAddUsuarioVIEW = new javax.swing.JTextField();
        inputSenhaUsuarioAddUsuarioVIEW = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        inputUsuarioAddUsuarioVIEW.setBackground(new java.awt.Color(51, 51, 51));
        inputUsuarioAddUsuarioVIEW.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(inputUsuarioAddUsuarioVIEW);
        inputUsuarioAddUsuarioVIEW.setBounds(6, 77, 679, 33);

        inputSenhaUsuarioAddUsuarioVIEW.setBackground(new java.awt.Color(51, 51, 51));
        inputSenhaUsuarioAddUsuarioVIEW.setForeground(new java.awt.Color(255, 255, 255));
        inputSenhaUsuarioAddUsuarioVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaUsuarioAddUsuarioVIEWActionPerformed(evt);
            }
        });
        getContentPane().add(inputSenhaUsuarioAddUsuarioVIEW);
        inputSenhaUsuarioAddUsuarioVIEW.setBounds(10, 140, 679, 33);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("CONCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 190, 120, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USUARIO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 90, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SENHA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 60, 17);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adicionar Usuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(123, 6, 330, 43);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("VOLTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(6, 182, 100, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\Tech Lines.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 280, 280);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\FundoPreto.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 710, 280);

        setSize(new java.awt.Dimension(720, 288));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //BOTAO DE ADICIONAR USUARIO
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //declarando valores que vao receber os inputs         
        String usuario;
        String senha;

        //colocando os valores dos inputs nas variaveis
        usuario = inputUsuarioAddUsuarioVIEW.getText();
        senha = inputSenhaUsuarioAddUsuarioVIEW.getText();

        //pegando os valores e setando
        UsuarioDTO usuarioDTO = new UsuarioDTO();
        usuarioDTO.setNome_usuario(usuario);
        usuarioDTO.setSenha_usuario(senha);
        

        //instanciando DAO que vai fazer a ação no banco
        AdminDAO adminDAO = new AdminDAO();
        adminDAO.cadastraUsuario(usuarioDTO);

        //mensagen de sucesso
        JOptionPane.showMessageDialog(null, "usuario criado com sucesso");

        //resirecioando para a tela de login
        this.dispose();
        MoneyControlADMINVIEW moneycontroladminVIEW = new MoneyControlADMINVIEW();
        moneycontroladminVIEW.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed
    
//BOTAO VOLTAR
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RelatorioUsuariosVIEW relatoriousariosVIEW = new RelatorioUsuariosVIEW();
        relatoriousariosVIEW.setVisible(true);
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void inputSenhaUsuarioAddUsuarioVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaUsuarioAddUsuarioVIEWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenhaUsuarioAddUsuarioVIEWActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputSenhaUsuarioAddUsuarioVIEW;
    private javax.swing.JTextField inputUsuarioAddUsuarioVIEW;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
