package com.moneycontrol.mavenproject1.VIEW.ADMIN;

import com.moneycontrol.mavenproject1.DAO.AdminDAO;
import com.moneycontrol.mavenproject1.DAO.ProcessDAO;
import com.moneycontrol.mavenproject1.DTO.AdminDTO;
import com.moneycontrol.mavenproject1.DTO.ProcessDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author SQi
 */
public class EditUsuarioVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirDespesaVIEW
     */
    public EditUsuarioVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_despesaTextFieldeditVIEW = new javax.swing.JTextField();
        backBTN_editDespesa = new javax.swing.JButton();
        btnBuscar_id_despesaVIEW = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        senhaTextField = new javax.swing.JTextField();
        nomeUsuarioTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id_conta_not_enable = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Usuario");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 6, 220, 43);

        id_despesaTextFieldeditVIEW.setBackground(new java.awt.Color(51, 51, 51));
        id_despesaTextFieldeditVIEW.setForeground(new java.awt.Color(255, 255, 255));
        id_despesaTextFieldeditVIEW.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID da conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        id_despesaTextFieldeditVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_despesaTextFieldeditVIEWActionPerformed(evt);
            }
        });
        getContentPane().add(id_despesaTextFieldeditVIEW);
        id_despesaTextFieldeditVIEW.setBounds(12, 71, 122, 39);

        backBTN_editDespesa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backBTN_editDespesa.setText("VOLTAR");
        backBTN_editDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN_editDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN_editDespesa);
        backBTN_editDespesa.setBounds(530, 10, 100, 28);

        btnBuscar_id_despesaVIEW.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBuscar_id_despesaVIEW.setText("BUSCAR");
        btnBuscar_id_despesaVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_id_despesaVIEWActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar_id_despesaVIEW);
        btnBuscar_id_despesaVIEW.setBounds(150, 70, 110, 28);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("CONCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(515, 241, 120, 28);

        senhaTextField.setBackground(new java.awt.Color(51, 51, 51));
        senhaTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(senhaTextField);
        senhaTextField.setBounds(6, 232, 267, 36);

        nomeUsuarioTextField.setBackground(new java.awt.Color(51, 51, 51));
        nomeUsuarioTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nomeUsuarioTextField);
        nomeUsuarioTextField.setBounds(6, 162, 267, 36);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOME DE USUARIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 140, 17);

        id_conta_not_enable.setBackground(new java.awt.Color(51, 51, 51));
        id_conta_not_enable.setForeground(new java.awt.Color(255, 255, 255));
        id_conta_not_enable.setEnabled(false);
        getContentPane().add(id_conta_not_enable);
        id_conta_not_enable.setBounds(450, 70, 50, 31);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SENHA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 60, 16);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID CONTA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 80, 80, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\Tech Lines.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 260, 300);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\FundoPreto.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 300);

        setSize(new java.awt.Dimension(668, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //BOTAO VOLTAR
    private void backBTN_editDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN_editDespesaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MoneyControlADMINVIEW moneycontroladminVIEW = new MoneyControlADMINVIEW();
        moneycontroladminVIEW.setVisible(true);
    }//GEN-LAST:event_backBTN_editDespesaActionPerformed

    private void id_despesaTextFieldeditVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_despesaTextFieldeditVIEWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_despesaTextFieldeditVIEWActionPerformed

    //BOTAO BUSCAR DESPESA
    private void btnBuscar_id_despesaVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_id_despesaVIEWActionPerformed
        // TODO add your handling code here:
        //criando variavel que vai pesquisar no banco
        int id_despesa;

        //passando string que veio do inputs para int
        id_despesa = Integer.parseInt(id_despesaTextFieldeditVIEW.getText());

        //chamando função de pesquisar
        AdminDAO adminDAO = new AdminDAO();
        AdminDTO adminDTO = adminDAO.pesquisaUsuario(id_despesa);
        if (adminDTO == null)
        {
            JOptionPane.showMessageDialog(null, "Despesa não encontrada !!!!!");
        } else
        {//preenchendo od inputs com os dados resgatados do banco  
            id_conta_not_enable.setText(String.valueOf(adminDTO.getId()));
            nomeUsuarioTextField.setText(adminDTO.getUsuarioAdmin());
            senhaTextField.setText(adminDTO.getSenhaAdmin());

        }
    }//GEN-LAST:event_btnBuscar_id_despesaVIEWActionPerformed

    //BOTAO DE EXCLUIR USUARIO
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id;
        String usuario;
        String senha;
       

        //pegando o texto dos imputs
        id = Integer.parseInt(id_conta_not_enable.getText());
        usuario = nomeUsuarioTextField.getText();
        senha = senhaTextField.getText();
       

        //instanciando novo DTO
        AdminDTO adminDTO = new AdminDTO();
        adminDTO.setId(id);
        adminDTO.setUsuarioAdmin(usuario);
        adminDTO.setSenhaAdmin(senha);
        

        //instanciando novo DAO que vai chamar a função
        AdminDAO adminDAO = new AdminDAO();

        //chamando a função
        adminDAO.editarUsuario(adminDTO);

        //mensagem de sucesso
        JOptionPane.showMessageDialog(null, "usuario editado com sucesso");

        //limpando inputs
        id_despesaTextFieldeditVIEW.setText("");
        id_conta_not_enable.setText("");        
        nomeUsuarioTextField.setText("");
        senhaTextField.setText("");
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN_editDespesa;
    private javax.swing.JButton btnBuscar_id_despesaVIEW;
    private javax.swing.JTextField id_conta_not_enable;
    private javax.swing.JTextField id_despesaTextFieldeditVIEW;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeUsuarioTextField;
    private javax.swing.JTextField senhaTextField;
    // End of variables declaration//GEN-END:variables
}
