package com.moneycontrol.mavenproject1.VIEW.ADMIN;

import com.moneycontrol.mavenproject1.DAO.ProcessDAO;
import com.moneycontrol.mavenproject1.DTO.ProcessDTO;
import javax.swing.JOptionPane;

public class ExcluirDespesaADMINVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirDespesaVIEW
     */
    public ExcluirDespesaADMINVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_despesaTextFieldEcluirVIEW_not_enable = new javax.swing.JTextField();
        backBTN_editDespesa = new javax.swing.JButton();
        btnBuscar_id_despesaVIEW = new javax.swing.JButton();
        id_despesa_not_enable = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Excluir Despesa");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 255, 47);

        id_despesaTextFieldEcluirVIEW_not_enable.setBackground(new java.awt.Color(51, 51, 51));
        id_despesaTextFieldEcluirVIEW_not_enable.setForeground(new java.awt.Color(255, 255, 255));
        id_despesaTextFieldEcluirVIEW_not_enable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID da conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        id_despesaTextFieldEcluirVIEW_not_enable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_despesaTextFieldEcluirVIEW_not_enableActionPerformed(evt);
            }
        });
        getContentPane().add(id_despesaTextFieldEcluirVIEW_not_enable);
        id_despesaTextFieldEcluirVIEW_not_enable.setBounds(10, 90, 122, 68);

        backBTN_editDespesa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backBTN_editDespesa.setText("VOLTAR");
        backBTN_editDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN_editDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN_editDespesa);
        backBTN_editDespesa.setBounds(399, 6, 100, 28);

        btnBuscar_id_despesaVIEW.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBuscar_id_despesaVIEW.setText("BUSCAR");
        btnBuscar_id_despesaVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_id_despesaVIEWActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar_id_despesaVIEW);
        btnBuscar_id_despesaVIEW.setBounds(160, 100, 100, 38);

        id_despesa_not_enable.setBackground(new java.awt.Color(51, 51, 51));
        id_despesa_not_enable.setForeground(new java.awt.Color(255, 255, 255));
        id_despesa_not_enable.setEnabled(false);
        id_despesa_not_enable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_despesa_not_enableActionPerformed(evt);
            }
        });
        getContentPane().add(id_despesa_not_enable);
        id_despesa_not_enable.setBounds(160, 180, 119, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID DESPESA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 192, 150, 29);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("EXCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(397, 225, 110, 28);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\Tech Lines.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 280, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\FundoPreto.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 550, 300);

        setSize(new java.awt.Dimension(558, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //BOTAO VOLTAR
    private void backBTN_editDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN_editDespesaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MoneyControlADMINVIEW moneycontroladminVIEW = new MoneyControlADMINVIEW();
        moneycontroladminVIEW.setVisible(true);
    }//GEN-LAST:event_backBTN_editDespesaActionPerformed

    private void id_despesaTextFieldEcluirVIEW_not_enableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_despesaTextFieldEcluirVIEW_not_enableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_despesaTextFieldEcluirVIEW_not_enableActionPerformed

    //BOTAO BUSCAR DESPESA
    private void btnBuscar_id_despesaVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_id_despesaVIEWActionPerformed
        // TODO add your handling code here:
        //criando variavel que vai pesquisar no banco
        int id_despesa;

        //passando string que veio do inputs para int
        id_despesa = Integer.parseInt(id_despesaTextFieldEcluirVIEW_not_enable.getText());

        //chamando função de pesquisar
        ProcessDAO processDAO = new ProcessDAO();
        ProcessDTO processDTO = processDAO.pesquisaDespesa(id_despesa);
        if (processDTO == null)
        {
            JOptionPane.showMessageDialog(null, "Despesa não encontrada !!!!!");
        } else
        {//preenchendo od inputs com os dados resgatados do banco  
            id_despesa_not_enable.setText(String.valueOf(processDTO.getId()));
        }
    }//GEN-LAST:event_btnBuscar_id_despesaVIEWActionPerformed

    private void id_despesa_not_enableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_despesa_not_enableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_despesa_not_enableActionPerformed

    //BOTAO DE EXCLUIR DESPESA
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //declarando id que vai receber o dado 
        int id_despesa;
        //covertendo o dado de string para int
        id_despesa = Integer.parseInt(id_despesaTextFieldEcluirVIEW_not_enable.getText());

        //instanciando novo DTO
        ProcessDTO processDTO = new ProcessDTO();
        processDTO.setId(id_despesa);

        //instanciando DAO para  chamar a função excluir
        ProcessDAO processDAO = new ProcessDAO();
        //chamando fumção
        processDAO.excluiDespesa(processDTO);
        JOptionPane.showMessageDialog(null, "despesa excluida ciom sucesso!!");

        //limpando campos
        id_despesaTextFieldEcluirVIEW_not_enable.setText("");
        id_despesa_not_enable.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN_editDespesa;
    private javax.swing.JButton btnBuscar_id_despesaVIEW;
    private javax.swing.JTextField id_despesaTextFieldEcluirVIEW_not_enable;
    private javax.swing.JTextField id_despesa_not_enable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
