package com.moneycontrol.mavenproject1.VIEW.ADMIN;

import com.moneycontrol.mavenproject1.DAO.AdminDAO;
import com.moneycontrol.mavenproject1.DTO.AdminDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class RelatorioUsuariosVIEW extends javax.swing.JFrame {

    private void relatorioUsuario() {
        //criando a classe que vai chamar a function
        AdminDAO adminDAO = new AdminDAO();
        String nome_usuario;
        nome_usuario = pesquisaUsuarioTextfieldVIEW.getText();

        List<AdminDTO> usuariosRelatorio = adminDAO.tirarRelatorioUsuario(nome_usuario);

        //criando variavel default table model para inserir content in tables
        DefaultTableModel tabelarelatorioUsuarios = (DefaultTableModel) tbRelatorioUsuariosVIEW.getModel();

        //limpando a tabela para nao dar duplicidade de coisas pesquisadas
        tabelarelatorioUsuarios.setNumRows(0);

        //percorrendo o list relatorio e inserir na tabela
        for (AdminDTO AdminDTO : usuariosRelatorio)
        {
            Object[] obj = new Object[]
            {
                AdminDTO.getId(),//id usuario
                AdminDTO.getUsuarioAdmin(), //nome usuario
                AdminDTO.getSenhaAdmin()//senha

            };

            //retornando oobjeto array
            tabelarelatorioUsuarios.addRow(obj);

        }

    }

    public RelatorioUsuariosVIEW() {
        initComponents();
        relatorioUsuario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRelatorioUsuariosVIEW = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pesquisaUsuarioTextfieldVIEW = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 499, 100, 28);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RELATÓRIO DE USUÁRIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 20, 480, 43);

        tbRelatorioUsuariosVIEW.setBackground(new java.awt.Color(51, 51, 51));
        tbRelatorioUsuariosVIEW.setForeground(new java.awt.Color(255, 255, 255));
        tbRelatorioUsuariosVIEW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USUARIO", "SENHA"
            }
        ));
        jScrollPane2.setViewportView(tbRelatorioUsuariosVIEW);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(6, 123, 923, 358);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 75, 170, 27);

        pesquisaUsuarioTextfieldVIEW.setBackground(new java.awt.Color(51, 51, 51));
        pesquisaUsuarioTextfieldVIEW.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        pesquisaUsuarioTextfieldVIEW.setForeground(new java.awt.Color(255, 255, 255));
        pesquisaUsuarioTextfieldVIEW.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pesquisaUsuarioTextfieldVIEWCaretUpdate(evt);
            }
        });
        pesquisaUsuarioTextfieldVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaUsuarioTextfieldVIEWActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisaUsuarioTextfieldVIEW);
        pesquisaUsuarioTextfieldVIEW.setBounds(205, 70, 724, 41);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("ADICIONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 500, 120, 28);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("EXCLUIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(840, 500, 100, 28);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("EDITAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(750, 500, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\Tech Lines.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 350, 580);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\olliv\\OneDrive\\Ambiente de Trabalho\\controle imagens\\FundoPreto.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 940, 580);

        setSize(new java.awt.Dimension(949, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //BOTAO VOLTAR
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MoneyControlADMINVIEW moneycontrolVIEW = new MoneyControlADMINVIEW();
        moneycontrolVIEW.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pesquisaUsuarioTextfieldVIEWCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pesquisaUsuarioTextfieldVIEWCaretUpdate
        // TODO add your handling code here:
        relatorioUsuario();
    }//GEN-LAST:event_pesquisaUsuarioTextfieldVIEWCaretUpdate

    private void pesquisaUsuarioTextfieldVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaUsuarioTextfieldVIEWActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pesquisaUsuarioTextfieldVIEWActionPerformed

    //BOTAO DE EDITAR USUARIO
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EditUsuarioVIEW editusuarioaVIEW = new EditUsuarioVIEW();
        editusuarioaVIEW.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    //BOTAO ADICIONAR USUARIO
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddUsuarioVIEW addusuarioVIEW = new AddUsuarioVIEW();
        addusuarioVIEW.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    //BOTAO EXCLUIR DESPESA
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ExcluirUsuarioVIEW excluirusuarioVIEW = new ExcluirUsuarioVIEW();
        excluirusuarioVIEW.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pesquisaUsuarioTextfieldVIEW;
    private javax.swing.JTable tbRelatorioUsuariosVIEW;
    // End of variables declaration//GEN-END:variables
}
